### ISSUE TITLE
Doesn't clear out removed records

### ISSUE THREAD

**Issue by Chilinot** [reststate/reststate-vuex#11]
If you first load a set of resources, then remove one in the set, then reload the resources. The one you removed will still be present in the Vuex store.

Looking over the code, it only seems to add or update records, never remove missing ones.

**Comment by Chilinot** [comment]
Sorry, i was unclear. If you have two browsers open with the same application, and load the resources in both. Then remove one of the resources in one of the browsers, and afterwards, reload in the other browser. The other browser will retrieve the correct list from the backend (missing the removed one), but doesn't remove the missing record from its own store.

**Comment by CodingItWrong** [comment]
Thanks for reporting this! I should be able to fix it pretty quickly.

To make sure I correctly handle your case: are you loading data with the `loadAll` action then accessing it with the `all` getter?

**Comment by Chilinot** [comment]
Yes, that is correct.

**Comment by CodingItWrong** [comment]
Thanks—I expect I should be able to fix this today.

**Comment by CodingItWrong** [comment]
OK, this should now be fixed and released in `0.0.6` — please give it a try and reopen this issue if not.

**Comment by Chilinot** [comment]
It works great!
