### ISSUE TITLE
Example for paging 

### ISSUE THREAD

**Issue by andreas83** [reststate/reststate-vuex#13]
Could you provide an example how to do proper pagination?
i tried the following which does not work. 

```
           const page = {
              'size': '100',
            };              
            this.$store.dispatch('sensorDatas/loadWhere', { page })
              .then(() => {
                const sensorData = this.$store.getters['sensorDatas/byId']({ page });
                console.log(sensorData);
              });   
```

**Comment by CodingItWrong** [comment]
I haven't tried doing pagination yet, but a few people have requested it so I should look into it. I'll try to do so soon.

In the meantime, you could check out the options argument to see if that works: https://vuex.reststate.org/reading-data.html#options

**Comment by CodingItWrong** [comment]
@andreas83 OK, I added some experimental pagination features in #14 — check out the description in that PR, install version `0.0.7`, and let me know what you think!

**Comment by andreas83** [comment]
Thanks for your really fast response. 
i played around it a little bit and i ended up with two questions:
1. is it possible to combine the page options with filters, for instance:
```
            this.loadPage({
                options: {
                    'page[number]': 1,
                    'page[size]': 1,
                },
                filter:{
                    'key' : "humidity"
                }
            });
```

Another question is about the loadById thing, i feel stupid, because it pretty straight forward, but i don't get it to work. 
i see the xhr request happened, but when i try to output the data from my getter i just get: 
({ id }) => state.records.find(r => r.id === id)

any hints would be highly appreciated, and sorry if its out of topic.

**Comment by andreas83** [comment]
I was able to answer 1. myself:
```
options: {
                    'page[number]': this.page,
                    'page[size]': 2,
                    'filter[key]': "temp"
                },
```

i still have no clue about my second question, but this should not matter, since the original feature request is working
