### ISSUE TITLE
Getter for current page number, total number of pages and page size

### ISSUE THREAD

**Issue by Niels-NTG** [reststate/reststate-vuex#22]
Currently there are getters for if there exists a previous and current page (which btw aren't properly documented at this point. I had to figure the existence of these out via this diff https://github.com/reststate/reststate-vuex/commit/93fffc6c9d9b4797782329b917e61ff58caaa80e), but none for these:

- current page number
- total number of pages (total number of items / items per page). 
- Items per page

I would argue this information is essential when making paginated frontends.

**Comment by CodingItWrong** [comment]
I don't believe JSON:API has a standard way to report these data items:

https://jsonapi.org/format/#fetching-pagination

Are those values returned in the response of the JSON:API server you're working with? If so, can you share an example response? Then I can look into how to expose that data.

**Comment by Niels-NTG** [comment]
I see. This is an example of what I'm working with:

```json
{
    "links": {
        "self": "\/api\/published_contents?page=8",
        "first": "\/api\/published_contents?page=1",
        "last": "\/api\/published_contents?page=35",
        "prev": "\/api\/published_contents?page=7",
        "next": "\/api\/published_contents?page=9"
    },
    "meta": {
        "totalItems": 1044,
        "itemsPerPage": 30,
        "currentPage": 8
    },
    "data": [
        {
            "id": "\/api\/published_contents\/4348",
            "type": "PublishedContent",
            "attributes": {
                "_id": 4348,
                "title": "foo"
            }
        },
        {
            "id": "\/api\/published_contents\/4349",
            "type": "PublishedContent",
            "attributes": {
                "_id": 4349,
                "title": "bar"
            }
        }
    ]
}
```

**Comment by CodingItWrong** [comment]
Thanks.

OK, here's my initial thought. The `meta` key on the response has the data, but so far the store module doesn't expose the concept of individual responses you get back. Instead, you just ask for records out of the store using getters.

I think I could just expose a `lastLoadResponse` getter that returns the last response you received for loading data. That way you could access the `meta.totalItems` property within the `lastLoadResponse` to get the data you need. But any time you dispatch another load action, that `lastLoadResponse` would be overridden.

Does that seem like it'd meet your needs?

**Comment by Niels-NTG** [comment]
That could work. Although I think I would rather have a special endpoint to access the `meta` object directly.

**Comment by CodingItWrong** [comment]
True, `meta` is central enough to JSON:API that that makes sense. I'll give it a shot and let you know.

**Comment by CodingItWrong** [comment]
Alright, I've released `0.0.9` which exposes a `lastMeta` getter. Tests seem to confirm it works the way you need, but please give it a try and see if it works for you. Once you OK it I'll add it and pagination in general to the docs 👍

**Comment by Niels-NTG** [comment]
Works great! Thanks for your quick response. 👍

**Comment by CodingItWrong** [comment]
Awesome, let me know if you run into any future edge cases with it, happy to brainstorm more features
