### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by geoidesic** [reststate/reststate-vuex#226]
Hi,

I fetched via Github Desktop. Ran `yarn install` then `yarn run serve`. Error:
```
yarn run v1.22.4
error Command "serve" not found
```

**Comment by CodingItWrong** [comment]
I think you probably ran the commands in the root directory of the project. The `example` is in a subdirectory that is a separate npm project, so you will want to run the commands in there:

```sh
$ cd reststate-vuex
$ cd example
$ yarn install
$ yarn run serve
```

I just retested the above and it works for me locally.

Please feel free to reopen this issue if the above doesn't work for you.
