### ISSUE TITLE
Tutorial enhancement: can't delete due to 500 internal server error

### ISSUE THREAD

**Issue by geoidesic** [reststate/reststate-vuex#227]
Hi,

I've been following along here: https://vuex.reststate.codingitwrong.com/tutorial.html
All worked fine till I got to delete. Delete just gives me a 500 internal server error.

This is because it only allows one to delete restaurants which were created by the tutorial, not those that were auto-created by HowToJson api on register.

It would be a nice timesaver to note this in the tutorial docs.

**Comment by CodingItWrong** [comment]
This was actually an error in the API server; it was intended to be able to delete those auto-created records. I just made a fix to it and confirmed that it works for me now, so it should work for anyone else in the future as well.

**Comment by CodingItWrong** [comment]
Thanks for reporting this problem!
