### ISSUE TITLE
Why are these mutations also wrapped as actions?

### ISSUE THREAD

**Issue by geoidesic** [reststate/reststate-vuex#229]
I notice this:https://github.com/reststate/reststate-vuex/blob/7948e7d95759d8b71f965f4a0a8cea8651a7d95a/src/reststate-vuex.js#L384

```
      delete({ commit }, record) {
        return client.delete(record).then(() => {
          commit("REMOVE_RECORD", record);
        });
      },

      storeRecord({ commit }, record) {
        commit("STORE_RECORD", record);
      },

      storeRelated({ commit }, { relatedIds, params }) {
        commit("STORE_RELATED", {
          relatedIds,
          params
        });
      },

      removeRecord({ commit }, record) {
        commit("REMOVE_RECORD", record);
      },

      resetState({ commit }) {
        commit("RESET_STATE");
      },
```

These just wrap mutations. Why have them? I think it's confusing. Rather keep actions as things that interact with the back-end and mutations as mutations.

I imagine this was done to avoid using `...mapMutations` but I think it detracts from clarity and makes things less explicit.

**Comment by geoidesic** [comment]
Relates to: https://github.com/reststate/reststate-vuex/issues/187

**Comment by CodingItWrong** [comment]
Delete does not just wrap mutations; it also hits the backend.

The other actions aren't part of the public documented interface of the code; they're private implementation details used by the library. As your app code shouldn't be using them, how they're implemented shouldn't matter to your app code.
