### ISSUE TITLE
How should one handle caching?

### ISSUE THREAD

**Issue by geoidesic** [reststate/reststate-vuex#254]
I notice that the documentation for `related` for example shows that first the related records must be loaded (which triggers an XHR) and then only can one use the get.

However what if you've already run the loader? I.e. what if the data already exists in the store? 
How do we first test for the data before running XHR needlessly?

**Comment by CodingItWrong** [comment]
The way to retrieve data from the store is the getter, so you could use the getter to see what data is in the store, then, if the data you expect isn't there, you could dispatch the action to load it.

**Comment by geoidesic** [comment]
That doesn't really solve the problem because you need to be able to tell the difference between "I looked on the server for the data and there isn't any data like that" vs. "I haven't looked at the server but the cache for that data is empty". Otherwise you're stuck in infinite recursion.
