### ISSUE TITLE
Question regarding updating store

### ISSUE THREAD

**Issue by andreas83** [reststate/reststate-vuex#27]
I added some websockets functionality to my app, 
so i wonder how i can change the stored data?

**Comment by CodingItWrong** [comment]
Sounds cool! What if I add actions that would allow you to update or remove a record in the store that you received via web socket? Do you send individual records over the web socket, or do you batch them up and send several at a time?

**Comment by andreas83** [comment]
at moment i just send one record in json api format via my socket server.
but i assume in some situation it can become handy to combine them into on chunk.

**Comment by CodingItWrong** [comment]
OK, to start out I've released 0.0.11 with `storeRecord` and `removeRecord` actions you can use. Details here: https://github.com/reststate/reststate-vuex/pull/28

Please give it a try and let me know if it meets your needs. After it's working I'll add actions to add and remove multiple records at once, and update the docs.

**Comment by CodingItWrong** [comment]
Closing as addressed; please feel free to reopen if anything is not working quite right with it
