### ISSUE TITLE
A question about the data return format

### ISSUE THREAD

**Issue by Alexanderwmc** [reststate/reststate-vuex#3]
Thanks for ur work， it's very nice! But I have a question about the data return format. In the `Json:api`,  it has many  top-level members, such as `data`, `meta`, `jsonapi` , `links`,  i saw that it only return member `data`：
```
 commit('STORE_RECORDS', result.data);        
``` 
how to use other top-level members. For example, i always return pagination information in the top-level member `meta`.

**Comment by CodingItWrong** [comment]
Hm, I'll need to think about the best way to handle that. Right now the store is organized around a permanent list of records, but the fields you mentioned returned by a single request is kind of transient; the next request might return different values.

What if I just return a Promise from the action that will resolve to the full response returned from the server? That way you could track and work with these fields however you like.

**Comment by inzanez** [comment]
I'm currently stumbling across the same issue.

Now I wonder: are there any objections to storing something like 'offset/limit/total' or 'page/pageSize/numberOfPages' alongside the records and upon fetching the collection (so not a single element), replace the complete collection with new data and store the paging information if available?

I mean: Is it really necessary to have a complete collection of what's been fetched ever in the past retained in the store? Or would it make sense to just retain the current state of what the user fetched last? This would exclude fetching of single records of course, they would need to be handled differently...

**Comment by CodingItWrong** [comment]
@inzanez The philosophy I'm taking for this library is to keep the past records fetched, yes. It's the idea of an identity map, keeping all the records in memory so they are available quickly as you use the app, even while you're fetching additional records. It's inspired by the way Ember Data is modeled.

For your use case, you might do better using `@reststate/client` directly, and implementing your Vuex stores in a different way. https://github.com/reststate/reststate-client

**Comment by CodingItWrong** [comment]
@inzanez OK, I added some experimental pagination features in #14 — check out the description in that PR, install version `0.0.7`, and let me know what you think!
