### ISSUE TITLE
Related getter returns old data after loadRelated options change

### ISSUE THREAD

**Issue by Niels-NTG** [reststate/reststate-vuex#34]
It seems that with the changes on how the library deals with relationships in version 0.0.13 something broke that causes data to be not updated when it's needed.

Or more concretely, an example:
```js
    computed: {
        products() {
            const products = this.$store.getters['products/related']({
                parent: {
                    id: this.organisationId,
                    type: 'organisation'
                }
            }) || []
            console.log(products)
            return products.map(({attributes}) => attributes)
        }
    },
    methods: {
        loadProducts() {
            this.$store.dispatch('products/loadRelated', {
                parent: {
                    id: this.organisationId,
                    type: 'organisation'
                },
                options: {
                    page: this.currentPage,
                    itemsPerPage: this.itemsPerPage,
                    sort: this.sort
                }
            }).then(() => {
                const meta = this.$store.getters['products/lastMeta']
                this.itemsPerPage = meta.itemsPerPage
                this.totalItems = meta.totalItems
            })
        }
    }
```
Initially the data gets loaded and getter like normal. But when I want to sort the data by the `name` property in ascending order I do another request with `loadProducts()` method, let me receive the correctly sorted data via `GET /organisations/1/products?page=1&itemsPerPage=30&sort=name`. When I access the data via the getter in the `products()` computed property, the old data gets returned. Same is true with pagination and itemsPerPage. So in general it seems like changing something in the request parameters isn't detected as new data.

**Comment by CodingItWrong** [comment]
Sorry about that problem, I definitely want to fix that to get it working.

You mentioned that this seems to break due to the changes in `0.0.13`. To help me track it down, can you double-check that this _does_ work correctly in `0.0.12`? I can see in the code why it might not be working now, but I'm not sure why it _would_ have been working in `0.0.12`

**Comment by Niels-NTG** [comment]
I was wrong. This hasn't been working in `0.0.10`, `0.0.11` and `0.0.12` either. So it probably never worked for me. When I insert a log at https://github.com/reststate/reststate-vuex/blob/master/src/reststate-vuex.js#L206 I can see that the `relatedIds` are sorted like they're suppose to. But they don't end up being stored correctly. Here's an example of my response for `GET GET /organisations/1/products?page=1&itemsPerPage=30&sort=name`:
```json
{
    "links": {
        "self": "\/organisation\/1\/products?itemsPerPage=30\u0026sort=-name"
    },
    "meta": {
        "totalItems": 4,
        "itemsPerPage": 30,
        "currentPage": 1
    },
    "data": [
        {
            "id": "\/products\/249",
            "type": "Product",
            "attributes": {
                "_id": 249,
                "name": "WisTrainer"
            },
            "relationships": {
                "organisations": {
                    "data": [
                        {
                            "type": "Organisation",
                            "id": "\/organisations\/1"
                        },
                        {
                            "type": "Organisation",
                            "id": "\/organisations\/176"
                        }
                    ]
                }
            }
        },
        {
            "id": "\/products\/1",
            "type": "Product",
            "attributes": {
                "_id": 1,
                "name": "trial"
            },
            "relationships": {
                "organisations": {
                    "data": [
                        {
                            "type": "Organisation",
                            "id": "\/organisations\/1"
                        },
                        {
                            "type": "Organisation",
                            "id": "\/organisations\/2"
                        }
                    ]
                }
            }
        },
        {
            "id": "\/products\/1023",
            "type": "Product",
            "attributes": {
                "_id": 1023,
                "name": "Premiumlicentie"
            },
            "relationships": {
                "organisations": {
                    "data": [
                        {
                            "type": "Organisation",
                            "id": "\/organisations\/1"
                        },
                        {
                            "type": "Organisation",
                            "id": "\/organisations\/29"
                        }
                    ]
                }
            }
        },
        {
            "id": "\/products\/1022",
            "type": "Product",
            "attributes": {
                "_id": 1022,
                "name": "Pluslicentie"
            },
            "relationships": {
                "organisations": {
                    "data": [
                        {
                            "type": "Organisation",
                            "id": "\/organisations\/1"
                        },
                        {
                            "type": "Organisation",
                            "id": "\/organisations\/2"
                        }
                    ]
                }
            }
        }
    ]
}
```

**Comment by Niels-NTG** [comment]
Interesting to note this bug doesn't occur when you sort if the total number of items is greater than fit on a page. e.g.
```json
    "meta": {
        "totalItems": 853,
        "itemsPerPage": 30,
        "currentPage": 1
    }
```
I suspect this is because the store gets populated with new ID's that have no overlap with those that where there before.

**Comment by CodingItWrong** [comment]
Thanks for researching. I'll work on adding this as a feature!

**Comment by CodingItWrong** [comment]
@Niels-NTG OK, `0.0.14` is released. For both `loadRelated` and `loadWhere`, it now caches results based on both the parameters and the `options`, so that if you pass in a different option (like a different `sort`) you'll get different results back. Give it a try and let me know if it works OK!

**Comment by Niels-NTG** [comment]
Sadly, `0.0.14` does not fix this issue. I don't see any changes.

**Comment by CodingItWrong** [comment]
The problem might be that I didn't explain some changes needed in the client code. The results of `loadRelated` are now cached and accessed based on all the data you pass into `loadRelated`. So if you call it like:

```
this.$store.dispatch('products/loadRelated', {
    parent: {
        id: this.organisationId,
        type: 'organisation'
    },
    options: {
        page: this.currentPage,
        itemsPerPage: this.itemsPerPage,
        sort: this.sort
    }
})
```

Then you would access the data with the same arguments:

```
this.$store.getters['products/related']({
  parent: {
      id: this.organisationId,
      type: 'organisation'
  },
  options: {
      page: this.currentPage,
      itemsPerPage: this.itemsPerPage,
      sort: this.sort
  }
})
```

Give that a try if you haven't already, and let me know if it works.

**Comment by Niels-NTG** [comment]
This does work… Except that this part:
```js
             .then(() => {
                const meta = this.$store.getters['products/lastMeta']
                this.itemsPerPage = meta.itemsPerPage
                this.totalItems = meta.totalItems
            })
```
makes the `product` computed property to return an empty array. Watching my console I see this first an empty array, followed by product filled array, directly followed by an empty array again.

**Comment by CodingItWrong** [comment]
I don't quite follow, where is the `product` computed property in this code sample?

**Comment by Niels-NTG** [comment]
Sorry. I ment to say `products` (plural). See my first comment.

**Comment by CodingItWrong** [comment]
Thanks, will dig in some more soon. Your project isn't open source for me to see it in use, is it?

**Comment by Niels-NTG** [comment]
Thanks

> Your project isn't open source for me to see it in use, is it?

I'm afraid not.

**Comment by CodingItWrong** [comment]
@Niels-NTG I reproduced your code, saw the problem, and I think I figured it out!

- When you request the related records in `loadProducts`, you do so based on the `itemsPerPage` in the component's data.
- When the response is returned, this causes the computed `products` to now have data to show.
- But then in your `then` function you overwrite `itemsPerPage` in the data with the returned value.
- This causes the computed `products` to rerun. But if `itemsPerPage` value is _different_, there is no cached data for that `itemsPerPage` value, so zero records are returned.

I would recommend doing some logging to see if the `itemsPerPage` value really is changing. If so, do you actually need to set it? If you do, it may be best to dispatch another `loadRelated` with the new `itemsPerPage` value—although there is a small chance of an infinite loop in the unlikely event that the server keeps returning a different `itemsPerPage` value each time.

I deployed the code I was running along with some console.log statements that show the sequence of what's happening: https://reststate-vuex-options-caching.netlify.com/

**Comment by Niels-NTG** [comment]
Thanks. `ItemsPerPage` doesn't need to be set since it's the frontend who's supposed to control this, not the backend. I fixed by removing it from this part:
```js
            .then(() => {
                const meta = this.$store.getters['products/lastMeta']
                this.totalItems = meta.totalItems
            })
```
