### ISSUE TITLE
[Feature request] Create related

### ISSUE THREAD

**Issue by Dylan-DutchAndBold** [reststate/reststate-vuex#59]
So far the library seems to support everything we need. Except creating related resources. We have an endpoint like this:

`POST /foo/{fooId}/bar`

There are two reasons why we'd want this:
- As per DDD we are only allowed to create the `Bar` relation through `Foo`.
- If we'd first have to create Bar and assign it to `Foo`, and for whatever reason that fails, we end up with a dangling `Bar`.

Is this something you would accept as a PR, a new `foo/createRelated` dispatch?

**Comment by CodingItWrong** [comment]
We can definitely add that feature, and if you'd like to PR it that'd be great! Or I could look into it in the next few days.

Couple questions:

- Currently I create related resources by calling `create()` and including the `relationships` key in a post to `/bar`. I'm not sure if every JSON:API backend supports this; does yours?

```json
{
  "type": "bar",
  "attributes": {...},
  "relationships": {
    "foo": {
      "data": {
        "type": "foo",
        "id": fooId,
      }
    }
  }
}
```

- If we do proceed with a `createRelated` action, we need to figure out where to get the URL from. Some JSON:API server implementations will provide the URL in a "links" key, like this:

```json
{
    "data": {
        "type": "foo",
        "id": fooId,
        "attributes": {...},
        "relationships": {
            "bar": {
                "links": {
                    "self": ".../foo/{fooId}/relationships/bar",
                    "related": ".../foo/{fooId}/bar"
                }
            }
        }
    }
}
```

So in this case `relationships.bar.links.related` would provide the URL that reststate-vuex would use. Does your backend provide that data? If not, I can provide a configuration option to provide the URL when you call `createRelated`

**Comment by Dylan-DutchAndBold** [comment]
About your first question, our platform does support it and I actually think it is a perfectly fine solution for this problem. It'll still allow for DDD. So I think this can be closed.

**Comment by CodingItWrong** [comment]
OK, I'm glad the first solution worked for you! I'll close this issue for now until someone is in a situation where there isn't a workaround.
