### ISSUE TITLE
spread operators give problems on mobile devices

### ISSUE THREAD

**Issue by TradeFace** [reststate/reststate-vuex#67]
Somehow the spread operator '...' used in reststate-vuex.js crashes the javascript. As a test I commented all the lines that have the operator and indeed JS keeps running. I have tested with numerous babel.config files. But nothing, so far, seems to resolve the problem. Strangely enough the spread operators in my own code doesn't break the runtime.

current babel.config.js
`module.exports = {
  presets: [
    ['@vue/app', {
      polyfills: [
        'es6.promise',
        'es6.symbol'       
      ]
    }],
  ]
}
`

my package.json
`{
  "name": "www",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@reststate/vuex": "^0.1.0",
    "axios": "^0.19.0",
    "core-js": "^2.6.5",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "register-service-worker": "^1.6.2",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.4.5",
    "@vue/cli-plugin-babel": "^3.8.0",
    "@vue/cli-plugin-eslint": "^3.8.0",
    "@vue/cli-plugin-pwa": "^3.8.0",
    "@vue/cli-service": "^3.8.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.1.0",
    "vue-template-compiler": "^2.6.10"
  }
}`

---
edit: fixed typo
---
additional: tested on chrome android, chrome iphone, safari iphone

**Comment by CodingItWrong** [comment]
Thanks for reporting this, I should be able to change the implementation to not use the spread operator, so it works in more transpiration setups. I'll try to have it ready in a few days!

**Comment by CodingItWrong** [comment]
OK, the spread operator has been removed in #72 and this has been released in version `0.1.1`—give it a try and see if this fixes the errors.

**Comment by TradeFace** [comment]
Works great! Thanks for that update!
